# Site settings
title: EmailVerifiers
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Unbiased reviews and comparisons of the best email verification services.
  Find the right tool for validating your email lists and preventing bounces.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emailverifiers.com" # the base hostname & protocol for your site
author: EmailVerifiers Team
logo: /assets/images/logo.svg
locale: en_US

# Build settings
plugins:
  - jekyll-feed
  - jekyll-tailwindcss

# Syntax highlighting
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - CLAUDE.md
   - bin

# Collections
collections:
  services:
    output: true
    permalink: /services/:name/
  comparisons:
    output: true
    permalink: /comparisons/:name/